"use strict";
var colors = require('colors');
const axios = require ("axios") ;
const apikey = "bd74f2b4733141299c0fcc77eb02de11"; // your api key to the api generated by the website
const getWeatherForecast = (weatherCond, location , time) => {
return new Promise (async (resolve, reject) => {
try {
const weatherConditions = await axios.get( 'https://api.weatherbit.io/v2.0/forecast/daily/',{
    /* get weather info from the api // write your api address access here , for instance : " http://api.apixu.com/v1/forecast.json" */
        params : {
        key: apikey ,
        city: location ,
        days : 3,
        units : "metric"
        }
    });

    resolve(weatherConditions.data)// returns back the results to the chatbot
    
}
catch (error) {
    Promise.reject(error).then(function() {
    }, function(error) {
      console.log("BOT:",error);
    });
}
}) ;
}

module.exports = getWeatherForecast ;