"use strict";
var colors = require('colors');
const axios = require ("axios") ;
const apikey = "95039ba6faeda7fb4576ee108e8f6791"; // your api key to the api generated by the website
const getWeather = location => {
return new Promise (async (resolve, reject) => {
try {
const weatherConditions = await axios.get( 'http://api.openweathermap.org/data/2.5/weather/',{
    /* get weather info from the api // write your api address access here , for instance : " http://api.apixu.com/v1/forecast.json" */
        params : {
        APPID: apikey ,
        q: location ,
        days : 3,
        units : "metric"
        }
    });

    resolve(weatherConditions.data) // returns back the results to the chatbot
    
}
catch (error) {
      reject(error);
}
});

}

module.exports = getWeather ;